import { AuditResult, Finding, RiskLevel } from '../core/types';

/**
 * Generates a professional Markdown audit report.
 */
export function formatMarkdown(result: AuditResult): string {
  const { summary } = result;
  const lines: string[] = [];

  lines.push('# Vault-Kit Smart Contract Security Audit Report');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| **Date** | ${new Date(result.timestamp).toLocaleString()} |`);
  lines.push(`| **Engine Version** | ${result.version} |`);
  lines.push(`| **Files Analyzed** | ${summary.filesAnalyzed} |`);
  lines.push(`| **Contracts Analyzed** | ${summary.contractsAnalyzed} |`);
  lines.push(`| **Lines of Code** | ${summary.linesOfCode} |`);
  lines.push('');

  // Security Score
  lines.push('## Security Score');
  lines.push('');
  lines.push(`### ${summary.score}/100 — ${riskEmoji(summary.riskLevel)} ${riskLabel(summary.riskLevel)}`);
  lines.push('');
  lines.push(renderMarkdownBar(summary.score));
  lines.push('');

  // Findings Summary
  lines.push('## Findings Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| Critical | **${summary.critical}** |`);
  lines.push(`| High | **${summary.high}** |`);
  lines.push(`| Medium | **${summary.medium}** |`);
  lines.push(`| Low | **${summary.low}** |`);
  lines.push(`| Informational | ${summary.informational} |`);
  lines.push(`| Gas Optimization | ${summary.gas} |`);
  lines.push(`| **Total** | **${summary.totalFindings}** |`);
  lines.push('');

  // Files
  lines.push('## Scope');
  lines.push('');
  lines.push('| File | Contracts | Lines | Findings |');
  lines.push('|------|-----------|-------|----------|');
  for (const file of result.files) {
    lines.push(
      `| \`${file.path}\` | ${file.contractNames.join(', ') || '-'} | ${file.linesOfCode} | ${file.findings.length} |`
    );
  }
  lines.push('');

  // Detailed Findings by Severity
  if (result.findings.length > 0) {
    lines.push('## Detailed Findings');
    lines.push('');

    const grouped = groupBySeverity(result.findings);

    for (const [severity, findings] of grouped) {
      lines.push(`### ${severityEmoji(severity)} ${severity.toUpperCase()} (${findings.length})`);
      lines.push('');

      for (const finding of findings) {
        lines.push(`#### ${finding.id}: ${finding.title}`);
        lines.push('');
        lines.push(`| | |`);
        lines.push(`|---|---|`);
        lines.push(`| **Severity** | ${severity.toUpperCase()} |`);
        lines.push(`| **Confidence** | ${finding.confidence} |`);
        lines.push(`| **Category** | ${finding.category} |`);
        lines.push(`| **Location** | \`${finding.location.file}:${finding.location.line}\` |`);
        if (finding.gasImpact) {
          lines.push(`| **Gas Impact** | ~${finding.gasImpact} gas |`);
        }
        lines.push('');
        lines.push('**Description:**');
        lines.push('');
        lines.push(finding.description);
        lines.push('');

        if (finding.location.snippet) {
          lines.push('**Code:**');
          lines.push('');
          lines.push('```solidity');
          lines.push(finding.location.snippet);
          lines.push('```');
          lines.push('');
        }

        lines.push('**Recommendation:**');
        lines.push('');
        lines.push(finding.recommendation);
        lines.push('');

        if (finding.references && finding.references.length > 0) {
          lines.push('**References:**');
          for (const ref of finding.references) {
            lines.push(`- ${ref}`);
          }
          lines.push('');
        }

        lines.push('---');
        lines.push('');
      }
    }
  }

  // Disclaimer
  lines.push('## Disclaimer');
  lines.push('');
  lines.push(
    'This report was generated by **Vault-Kit** automated static analysis engine. ' +
    'Static analysis is a valuable first step in security assessment but cannot detect all ' +
    'vulnerability classes (e.g., business logic errors, economic attacks). ' +
    'This report should not be considered a substitute for a comprehensive manual audit ' +
    'by experienced security researchers.'
  );
  lines.push('');
  lines.push('---');
  lines.push('*Generated by Vault-Kit v' + result.version + '*');

  return lines.join('\n');
}

function groupBySeverity(findings: Finding[]): Map<string, Finding[]> {
  const map = new Map<string, Finding[]>();
  for (const f of findings) {
    if (!map.has(f.severity)) map.set(f.severity, []);
    map.get(f.severity)!.push(f);
  }
  return map;
}

function renderMarkdownBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  return `\`[${'#'.repeat(filled)}${'-'.repeat(empty)}]\` ${score}/100`;
}

function riskEmoji(risk: RiskLevel): string {
  switch (risk) {
    case 'PASS':          return '(PASS)';
    case 'LOW_RISK':      return '(LOW)';
    case 'MEDIUM_RISK':   return '(MED)';
    case 'HIGH_RISK':     return '(HIGH)';
    case 'CRITICAL_RISK': return '(CRIT)';
    default: return '';
  }
}

function riskLabel(risk: RiskLevel): string {
  switch (risk) {
    case 'PASS':          return 'No significant issues found';
    case 'LOW_RISK':      return 'Minor issues identified';
    case 'MEDIUM_RISK':   return 'Issues requiring attention';
    case 'HIGH_RISK':     return 'Significant vulnerabilities detected';
    case 'CRITICAL_RISK': return 'Severe vulnerabilities — do not deploy';
    default: return risk;
  }
}

function severityEmoji(severity: string): string {
  switch (severity) {
    case 'critical':      return '[CRITICAL]';
    case 'high':          return '[HIGH]';
    case 'medium':        return '[MEDIUM]';
    case 'low':           return '[LOW]';
    case 'informational': return '[INFO]';
    case 'gas':           return '[GAS]';
    default:              return '';
  }
}
