import { AuditResult, Finding, Severity, RiskLevel } from '../core/types';
import { formatMarkdown } from './formatter';

export type OutputFormat = 'json' | 'markdown' | 'text';

export function generateReport(result: AuditResult, format: OutputFormat): string {
  switch (format) {
    case 'json':
      return generateJSON(result);
    case 'markdown':
      return formatMarkdown(result);
    case 'text':
      return generateText(result);
    default:
      return generateText(result);
  }
}

function generateJSON(result: AuditResult): string {
  return JSON.stringify(result, null, 2);
}

function generateText(result: AuditResult): string {
  const lines: string[] = [];
  const { summary } = result;

  // Header
  lines.push('');
  lines.push('='.repeat(72));
  lines.push('  VAULT-KIT SMART CONTRACT SECURITY AUDIT REPORT');
  lines.push('='.repeat(72));
  lines.push('');
  lines.push(`  Date:       ${new Date(result.timestamp).toLocaleString()}`);
  lines.push(`  Version:    ${result.version}`);
  lines.push(`  Files:      ${summary.filesAnalyzed}`);
  lines.push(`  Contracts:  ${summary.contractsAnalyzed}`);
  lines.push(`  Lines:      ${summary.linesOfCode}`);
  lines.push('');

  // Security Score
  lines.push('-'.repeat(72));
  lines.push('  SECURITY SCORE');
  lines.push('-'.repeat(72));
  lines.push('');
  lines.push(`  Score:  ${summary.score}/100  [${riskBadge(summary.riskLevel)}]`);
  lines.push('');
  lines.push(renderScoreBar(summary.score));
  lines.push('');

  // Summary
  lines.push('-'.repeat(72));
  lines.push('  FINDINGS SUMMARY');
  lines.push('-'.repeat(72));
  lines.push('');
  lines.push(`  ${severityIcon('critical')} Critical:        ${padCount(summary.critical)}`);
  lines.push(`  ${severityIcon('high')} High:            ${padCount(summary.high)}`);
  lines.push(`  ${severityIcon('medium')} Medium:          ${padCount(summary.medium)}`);
  lines.push(`  ${severityIcon('low')} Low:             ${padCount(summary.low)}`);
  lines.push(`  ${severityIcon('informational')} Informational:   ${padCount(summary.informational)}`);
  lines.push(`  ${severityIcon('gas')} Gas:             ${padCount(summary.gas)}`);
  lines.push(`  ${'='.repeat(30)}`);
  lines.push(`  Total:             ${padCount(summary.totalFindings)}`);
  lines.push('');

  // Files analyzed
  lines.push('-'.repeat(72));
  lines.push('  FILES ANALYZED');
  lines.push('-'.repeat(72));
  lines.push('');
  for (const file of result.files) {
    const contracts = file.contractNames.length > 0
      ? ` (${file.contractNames.join(', ')})`
      : '';
    lines.push(`  ${file.path}${contracts}`);
    lines.push(`    Lines: ${file.linesOfCode} | Findings: ${file.findings.length} | Solidity: ${file.solidityVersion || 'unknown'}`);
  }
  lines.push('');

  // Detailed Findings
  if (result.findings.length > 0) {
    lines.push('-'.repeat(72));
    lines.push('  DETAILED FINDINGS');
    lines.push('-'.repeat(72));

    let currentSeverity = '';

    for (const finding of result.findings) {
      if (finding.severity !== currentSeverity) {
        currentSeverity = finding.severity;
        lines.push('');
        lines.push(`  --- ${finding.severity.toUpperCase()} ---`);
      }

      lines.push('');
      lines.push(`  [${finding.id}] ${finding.title}`);
      lines.push(`  Severity:   ${severityIcon(finding.severity)} ${finding.severity.toUpperCase()}`);
      lines.push(`  Confidence: ${finding.confidence}`);
      lines.push(`  Category:   ${finding.category}`);
      lines.push(`  Location:   ${finding.location.file}:${finding.location.line}`);
      lines.push('');
      lines.push(`  Description:`);
      wrapText(finding.description, 66).forEach(l => lines.push(`    ${l}`));
      lines.push('');

      if (finding.location.snippet) {
        lines.push(`  Code:`);
        finding.location.snippet.split('\n').forEach(l => lines.push(`    ${l}`));
        lines.push('');
      }

      lines.push(`  Recommendation:`);
      wrapText(finding.recommendation, 66).forEach(l => lines.push(`    ${l}`));

      if (finding.references && finding.references.length > 0) {
        lines.push('');
        lines.push(`  References:`);
        for (const ref of finding.references) {
          lines.push(`    - ${ref}`);
        }
      }

      if (finding.gasImpact) {
        lines.push(`  Gas Impact: ~${finding.gasImpact} gas per occurrence`);
      }

      lines.push('');
      lines.push(`  ${'- '.repeat(36)}`);
    }
  } else {
    lines.push('');
    lines.push('  No findings detected. The analyzed contracts appear to follow');
    lines.push('  best practices for the checks performed.');
  }

  lines.push('');
  lines.push('='.repeat(72));
  lines.push('  END OF REPORT');
  lines.push('');
  lines.push('  This report was generated by Vault-Kit static analysis engine.');
  lines.push('  Static analysis cannot guarantee the absence of vulnerabilities.');
  lines.push('  A manual review by experienced auditors is always recommended.');
  lines.push('='.repeat(72));
  lines.push('');

  return lines.join('\n');
}

function renderScoreBar(score: number): string {
  const width = 40;
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  const bar = '#'.repeat(filled) + '-'.repeat(empty);
  return `  [${bar}] ${score}/100`;
}

function severityIcon(severity: string): string {
  switch (severity) {
    case 'critical': return '[!!!]';
    case 'high':     return '[!! ]';
    case 'medium':   return '[!  ]';
    case 'low':      return '[.  ]';
    case 'informational': return '[i  ]';
    case 'gas':      return '[$  ]';
    default:         return '[   ]';
  }
}

function riskBadge(risk: RiskLevel): string {
  switch (risk) {
    case 'PASS':          return 'PASS - No significant issues';
    case 'LOW_RISK':      return 'LOW RISK - Minor issues found';
    case 'MEDIUM_RISK':   return 'MEDIUM RISK - Issues require attention';
    case 'HIGH_RISK':     return 'HIGH RISK - Significant vulnerabilities';
    case 'CRITICAL_RISK': return 'CRITICAL - Severe vulnerabilities detected';
    default:              return risk;
  }
}

function padCount(n: number): string {
  return String(n).padStart(3);
}

function wrapText(text: string, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    if (current.length + word.length + 1 > maxWidth) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines;
}
